In [2]:
# External packages: pre implemented python code by someone

In [3]:
import pandas as pd

In [4]:
# 1. create a dataframe
pd.DataFrame(
    rows and columns
)

In [6]:
pd.DataFrame(
    {
        "col1" : [1,2,3],
        "col2" : ['a','b','c']
    }
)

   col1 col2
0     1    a
1     2    b
2     3    c

In [16]:
pd.DataFrame(
    {
        "col1" : [1,2,3,4],
        "col2" : ('a','b','c','d'),
        "col3" : "hemr"
    }
)

   col1 col2  col3
0     1    a  hemr
1     2    b  hemr
2     3    c  hemr
3     4    d  hemr

In [18]:
data = {
        "col1" : [1,2,3,4],
        "col2" : ('a','b','c','d'),
        "col3" : "hemr"
    }
pd.DataFrame(
    data
)

   col1 col2  col3
0     1    a  hemr
1     2    b  hemr
2     3    c  hemr
3     4    d  hemr

In [21]:
df = pd.DataFrame(
    {
        "col1" : [1,2,3,4],
        "col2" : ('a','b','c','d'),
    }
)

In [22]:
df

   col1 col2
0     1    a
1     2    b
2     3    c
3     4    d

In [23]:
df['col3'] = [12,13,15,12]

In [24]:
df

   col1 col2  col3
0     1    a    12
1     2    b    13
2     3    c    15
3     4    d    12

In [26]:
df.values

array([[1, 'a', 12],
       [2, 'b', 13],
       [3, 'c', 15],
       [4, 'd', 12]], dtype=object)

In [27]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [28]:
df.col2

0    a
1    b
2    c
3    d
Name: col2, dtype: str

In [29]:
df.col3[2]

np.int64(15)

In [30]:
# indexing
1. loc
2. iloc