In [2]:
import numpy as np
import pandas as pd

In [299]:
# wap to add list elements of array belonging to nth index and convert to new list 
l1 = [1,2,3,4,5]
l2 = [4,5,6,6,7]

In [300]:
l3 = []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
print(l3)

[5, 7, 9, 10, 12]

In [301]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [191]:
a+b

array([3, 5, 7, 9])

In [192]:
a-b

array([-1, -1, -1, -1])

In [193]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [194]:
a*2

array([2, 4, 6, 8])

In [195]:
a**2

array([ 1,  4,  9, 16])

In [196]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
np.zeros(2)

array([0., 0.])

In [198]:
np.ones(4)

array([1., 1., 1., 1.])

In [199]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [200]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [201]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [202]:
np.arange(1,16,3)

array([ 1,  4,  7, 10, 13])

In [203]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [204]:
arr = np. array([2,3,4,5,6])

In [205]:
arr

array([2, 3, 4, 5, 6])

In [206]:
arr.shape

(5,)

In [207]:
arr = np. array([[2,3,4,5,6]])

In [208]:
arr

array([[2, 3, 4, 5, 6]])

In [209]:
arr.shape

(1, 5)

In [210]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [211]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [212]:
#row and column
arr.shape

(2, 5)

In [213]:
# number of dimensions
arr.ndim

2

In [214]:
# size of array
arr.size

10

In [215]:
# data type of array
arr.dtype

dtype('int64')

In [216]:
# memory size
arr.itemsize

8

In [217]:
arr1 = np.array([[True,True,False]])

In [218]:
arr1.dtype

dtype('bool')

In [219]:
arr1.itemsize

1

In [220]:
arr2 = np.array([[True,True,"a"]])

In [221]:
arr2.dtype

dtype('<U5')

In [222]:
arr2.itemsize

20

In [223]:
arr2.item

In [224]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [225]:
# indexing and slicing
arr[1]

array([2, 3, 4, 5, 6])

In [226]:
arr[1,2]

np.int64(4)

In [227]:
#start:stop
arr[1:3]

array([[2, 3, 4, 5, 6]])

In [228]:
arr = np. array([[1,2,3,4,5]])

In [229]:
arr[0]

array([1, 2, 3, 4, 5])

In [230]:
arr[:2]

array([[1, 2, 3, 4, 5]])

In [231]:
arr[0:]

array([[1, 2, 3, 4, 5]])

In [232]:
#entire row and fixed column
arr[:,1]

array([2])

In [233]:
#row, column
arr[:,0:2]

array([[1, 2]])

In [234]:
arr = np. array([[1,2],[3,4],[5,6]])

In [235]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [236]:
arr[0:2,:]

array([[1, 2],
       [3, 4]])

In [237]:
arr[1:2,:]

array([[3, 4]])

In [238]:
arr[1:3,:]

array([[3, 4],
       [5, 6]])

In [239]:
arr = np. array([[1,2,9],[3,4,2],[5,6,7]])

In [240]:
arr

array([[1, 2, 9],
       [3, 4, 2],
       [5, 6, 7]])

In [241]:
arr[1:3,1:3]

array([[4, 2],
       [6, 7]])

In [242]:
# mathematical operations
arr1 = np. array([[1,2,9],[3,4,2]])
arr2 = np. array([[3,1,2],[5,6,4]])

In [243]:
arr1+arr2

array([[ 4,  3, 11],
       [ 8, 10,  6]])

In [244]:
arr1-arr2

array([[-2,  1,  7],
       [-2, -2, -2]])

In [245]:
arr1*arr2

array([[ 3,  2, 18],
       [15, 24,  8]])

In [246]:
arr1/arr2

array([[0.33333333, 2.        , 4.5       ],
       [0.6       , 0.66666667, 0.5       ]])

In [247]:
arr1 **2

array([[ 1,  4, 81],
       [ 9, 16,  4]])

In [248]:
# reshaping
arr = np.array([[1,2,3,4]])

In [249]:
arr

array([[1, 2, 3, 4]])

In [250]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [251]:
arr = np.array([[1,2,3,4,2,6,7]])

In [252]:
arr

array([[1, 2, 3, 4, 2, 6, 7]])

In [253]:
arr.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [6],
       [7]])

In [254]:
# practice assignment

In [255]:
# create a Numpy array of integers from  1 to 20 (inclusive).Then:
# 1. Reshape it into a 4×5 array.
# 2. Print its shape, number of dimensions, and total size.
# 3. Extract the second row and the last column separately.

In [256]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [257]:
new_arr = arr.reshape(4,5)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [258]:
new_arr.size

20

In [259]:
new_arr.shape

(4, 5)

In [260]:
new_arr.ndim

2

In [261]:
# Using NumPy's built-in generators (not manual lists):
# 1. Create a 3×3 identity matrix using np.eye() .
# 2. Create an array of 10 evenly spaced values between 0 and 1 using np.linspace() .
# 3. Create a 2×4 array filled entirely with the value 7 using np.full() .

In [262]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [263]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [264]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [265]:
# Create two NumPy arrays: a = np.array([10, 20, 30, 40]) and b = np.array([1, 2, 3, 4]) .
# 1. Compute their element-wise sum, difference, product, and quotient.
# 2. Create a 4×4 matrix by broadcasting a as rows and adding b as a column vector (i.e. a + b.reshape(4,1) ). Print
# the result.
# 3. Explain in one sentence (as a code comment) what broadcasting rule made step 2 possible.

In [266]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [267]:
# sum
a+b

array([11, 22, 33, 44])

In [268]:
# difference
a-b

array([ 9, 18, 27, 36])

In [269]:
# quotient
a/b

array([10., 10., 10., 10.])

In [270]:
# reshape a+b
reshape_result = a+b.reshape(4,1)
reshape_result

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [271]:
# Broadcasting works because the 1D array a is automatically expanded across rows to match b's (4,1) column shape.

In [272]:
# Using np.random.seed(10) , generate arr = np.random.randint(1, 100, size=20) .
# 1. Print all elements greater than 50 using boolean indexing.
# 2. Replace all elements less than 20 with 0 (in place).
# 3. Compute the mean, median, standard deviation, minimum, and maximum of the updated array.

In [273]:
np.random.seed(10)
arr1 = np.random.randint(1, 100, size=20)
print(arr1)

[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79]

In [274]:
print(arr1[arr1 > 50])

[65 90 94 74 55 89 63 73 79]

In [275]:
arr1[arr1<20] = 0
print(arr1)

[ 0  0 65 29 90 94 30  0 74  0 41 37  0  0 55 89 63 34 73 79]

In [276]:
np.mean(arr1)

np.float64(42.65)

In [277]:
np.median(arr1)

np.float64(39.0)

In [278]:
np.std(arr1)

np.float64(33.681263337351226)

In [279]:
np.min(arr1)

np.int32(0)

In [280]:
np.max(arr1)

np.int32(94)

In [281]:
# Create two 3×3 matrices:
# A = np.array([[2, 0, 1], [1, 3, 2], [4, 1, 5]])
# B = np.array([[1, 2, 0], [0, 1, 2], [2, 0, 1]])
# Compute the matrix product A · B using np.dot() or the @ operator (not element-wise multiplication).
# Compute the transpose of A and the determinant of A using np.linalg.det() .
# Check whether A is invertible (based on its determinant), and if so, compute its inverse using np.linalg.inv() .
# Verify your result by multiplying A with its inverse and confirming you get (approximately) the identity matrix.

In [4]:
A = np.array([[2, 0, 1], [1, 3, 2], [4, 1, 5]])
B = np.array([[1, 2, 0], [0, 1, 2], [2, 0, 1]])

In [5]:
np.dot(A,B)

array([[ 4,  4,  1],
       [ 5,  5,  8],
       [14,  9,  7]])

In [6]:
np.transpose(A)

array([[2, 1, 4],
       [0, 3, 1],
       [1, 2, 5]])

In [7]:
det_A = np.linalg.det(A)
det_A

np.float64(15.000000000000007)

In [16]:
if not np.isclose(det_A, 0):
    print("\nA is invertible.")

else:
    print("\nA is not invertible.")

A is invertible.

In [11]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.86666667,  0.06666667, -0.2       ],
       [ 0.2       ,  0.4       , -0.2       ],
       [-0.73333333, -0.13333333,  0.4       ]])

In [14]:
# Verify A × A⁻¹
identity = A @ A_inverse
identity

array([[ 1.00000000e+00, -2.77555756e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16, -2.77555756e-17,  1.00000000e+00]])

In [15]:
print(np.allclose(identity, np.eye(3)))

True

In [292]:
# pandas practice questions

In [302]:
# Create a Pandas Series from the list [45, 78, 23, 90, 56] with custom index labels ["Math", "Science",
# "English", "History", "Art"] .
# 1. Print the value corresponding to "Science" .
# 2. Print all subjects where the score is above 50.
# 3. Sort the Series by value in ascending order.

In [307]:
scores = pd.Series([45, 78, 23, 90, 56],
                  index=["Math", "Science","English", "History", "Art"])

In [308]:
print(scores)

Math       45
Science    78
English    23
History    90
Art        56
dtype: int64

In [313]:
print(scores[scores > 50])

Science    78
History    90
Art        56
dtype: int64

In [314]:
print(scores.sort_values())

English    23
Math       45
Art        56
Science    78
History    90
dtype: int64

In [315]:
print(scores["Science"])

78

In [ ]:
# Assume you have a CSV file named sales_data.csv with columns ["OrderID", "Product", "Quantity",
# "Price", "Date"] .
# 1. Load it into a DataFrame using pd.read_csv() .
# 2. Display the first 5 rows, the last 5 rows, and a summary using .info() .
# 3. Check for and count any missing values in each column using .isnull().sum() .

In [36]:
df = pd.read_excel("Product-Sales-Region.xlsx")

In [37]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [38]:
df.tail()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[us]
 1   Region         1500 non-null   str
 2   Product        1500 non-null   str
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   str
 6   CustomerType   1500 non-null   str
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   str
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   str
 11  Promotion      1130 non-null   str
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   str
 14  CustomerName   1500 non-null   str
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[us]
 17  DeliveryDate   1500 non-null   datetime64[us]
 18  RegionManager  1500 non-null   str
dtypes: datetime64[us](3), float64(4), int64(2), str(10)
memory usage: 222.8 KB

In [40]:
df.isnull()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [41]:
df.isna().sum()

Date               0
Region             0
Product            0
Quantity           0
UnitPrice          0
StoreLocation      0
CustomerType       0
Discount           0
Salesperson        0
TotalPrice         0
PaymentMethod      0
Promotion        370
Returned           0
OrderID            0
CustomerName       0
ShippingCost       0
OrderDate          0
DeliveryDate       0
RegionManager      0
dtype: int64

In [42]:
# Continuing with the sales_data.csv DataFrame from Question 7:
# 1. Drop any rows where Quantity or Price is missing.
# 2. Create a new column "TotalAmount" as Quantity × Price .
# 3. Convert the Date column to datetime format using pd.to_datetime() and extract the month into a new column
# "Month" .

In [43]:
df.dropna(subset=['Quantity','UnitPrice'])

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [44]:
df['Total Amount'] = df['Quantity']*df['UnitPrice']

In [45]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68

In [46]:
pd.to_datetime(df['Date'])

0      2023-02-23
1      2024-12-19
2      2023-05-10
3      2025-02-26
4      2023-06-24
          ...
1495   2025-02-17
1496   2024-01-11
1497   2024-07-27
1498   2024-12-03
1499   2025-05-09
Name: Date, Length: 1500, dtype: datetime64[us]

In [47]:
df['Month'] = pd.to_datetime(df['Date']).dt.month

In [48]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [49]:
# Using the cleaned DataFrame from Question 8:
# 1. Group the data by Product and calculate the total TotalAmount and average Quantity sold for each product.
# 2. Find the top 3 products by total revenue.
# 3. Group by Month and plot (or print) the total revenue trend across months.

In [50]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [51]:
product_summary = df.groupby('Product').agg(
    Total_Revenue = ('TotalPrice','sum'),
    Average_Quantity = ('Quantity', 'mean')
)

In [52]:
print(product_summary)

         Total_Revenue  Average_Quantity
Product
Chair      622589.4780         10.153110
Desk       555266.6645          9.787440
Laptop     684417.2415         10.654867
Monitor    651629.3925         10.268868
Phone      497162.8510         10.102564
Printer    684387.4155         11.071090
Tablet     684539.3855         10.737500

In [58]:
top3_product = product_summary.sort_values(
    'Total_Revenue',
    ascending=False
).head(3)

In [59]:
print(top3_product)

         Total_Revenue  Average_Quantity
Product
Tablet     684539.3855         10.737500
Laptop     684417.2415         10.654867
Printer    684387.4155         11.071090

In [60]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [62]:
Monthly_revenue = df.groupby('Month')['TotalPrice'].sum()

In [63]:
print(Monthly_revenue)

Month
1     498358.5015
2     415057.8135
3     532090.9535
4     443318.7265
5     402408.0255
6     434261.6690
7     280050.0475
8     289639.0035
9     282114.6490
10    256612.8970
11    283330.6200
12    262749.5220
Name: TotalPrice, dtype: float64

In [65]:
# You have two DataFrames:

# Merge orders and customers on CustomerID using an inner join.
# Create a pivot table showing total Amount spent per City .
# Identify the customer with the highest total spending and print their name and city.

In [73]:
orders = pd.DataFrame({
    "OrderID": [1, 2, 3, 4, 5],
    "CustomerID": [101, 102, 101, 103, 102],
    "Amount": [250, 450, 300, 600, 150]
})
customers = pd.DataFrame({
    "CustomerID": [101, 102, 103],
    "Name": ["Sita", "Ramesh", "Gita"],
    "City": ["Kathmandu", "Pokhara", "Lalitpur"]
})

In [74]:
df= pd.merge(
    orders,
    customers,
    on='CustomerID',
    how='inner'
)

In [78]:
df

   OrderID  CustomerID  Amount    Name       City
0        1         101     250    Sita  Kathmandu
1        2         102     450  Ramesh    Pokhara
2        3         101     300    Sita  Kathmandu
3        4         103     600    Gita   Lalitpur
4        5         102     150  Ramesh    Pokhara

In [79]:
pd.pivot_table(df,values='Amount', index='City', aggfunc='sum')

           Amount
City
Kathmandu     550
Lalitpur      600
Pokhara       600

In [89]:
df

   OrderID  CustomerID  Amount    Name       City
0        1         101     250    Sita  Kathmandu
1        2         102     450  Ramesh    Pokhara
2        3         101     300    Sita  Kathmandu
3        4         103     600    Gita   Lalitpur
4        5         102     150  Ramesh    Pokhara

In [98]:
df.groupby(['Name','City'])['Amount'].sum()

Name    City
Gita    Lalitpur     600
Ramesh  Pokhara      600
Sita    Kathmandu    550
Name: Amount, dtype: int64

In [99]:
# Create a DataFrame from the following dictionary of student data:

# Display the column names, index, and data types.
# Select and print only the Name and Marks columns.
# Select the row for "Chirag" using both .loc and .iloc .

In [54]:
data = {
"Name": ["Aarav", "Bina", "Chirag", "Divya", "Esha"],
"Age": [21, 22, 20, 23, 21],
"Marks": [85, 62, 90, 75, 68]
}

In [55]:
df = pd.DataFrame(data)

In [56]:
df

     Name  Age  Marks
0   Aarav   21     85
1    Bina   22     62
2  Chirag   20     90
3   Divya   23     75
4    Esha   21     68

In [57]:
df[['Name','Marks']]

     Name  Marks
0   Aarav     85
1    Bina     62
2  Chirag     90
3   Divya     75
4    Esha     68

In [58]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [59]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [60]:
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [61]:
# df.loc[2]
df.loc[2:2]

     Name  Age  Marks
2  Chirag   20     90

In [62]:
df.iloc[2:3]

     Name  Age  Marks
2  Chirag   20     90

In [63]:
# Using the same student DataFrame from Question 11:
# Add a new column "Grade" where Marks ≥ 75 is "A" , otherwise "B" .
# Rename the column "Marks" to "Score" .
# Drop the "Age" column and print the resulting DataFrame.

In [64]:
df

     Name  Age  Marks
0   Aarav   21     85
1    Bina   22     62
2  Chirag   20     90
3   Divya   23     75
4    Esha   21     68

In [65]:
# df["Grade"]=np.where(df['Marks']>=57,"A" ,"B")
df["Grade"] = df["Marks"].apply(lambda x: "A" if x >= 57 else "B")

In [66]:
df

     Name  Age  Marks Grade
0   Aarav   21     85     A
1    Bina   22     62     A
2  Chirag   20     90     A
3   Divya   23     75     A
4    Esha   21     68     A

In [67]:
df= df.rename(columns={"Marks":"Scores"})

In [68]:
df

     Name  Age  Scores Grade
0   Aarav   21      85     A
1    Bina   22      62     A
2  Chirag   20      90     A
3   Divya   23      75     A
4    Esha   21      68     A

In [69]:
df = df.drop(columns =["Age"])
df

     Name  Scores Grade
0   Aarav      85     A
1    Bina      62     A
2  Chirag      90     A
3   Divya      75     A
4    Esha      68     A

In [70]:
# You have a DataFrame df of employee records with columns ["EmpID", "Department", "Salary",
# "YearsExperience"] for 15 employees across 3 departments ( "Sales" , "IT" , "HR" ).
# Filter employees with YearsExperience > 5 and display only EmpID , Department , and Salary .
# Sort the full DataFrame first by Department (ascending) and then by Salary (descending).
# Use .apply() with a lambda function to create a new column "SeniorityLevel" : "Senior" if experience > 7,
# "Mid" if 3–7, otherwise "Junior" .

In [71]:
data = {
    "EmpID": [101, 102, 103, 104, 105, 
              106, 107, 108, 109, 110,
              111, 112, 113, 114, 115],

    "Department": ["Sales", "IT", "HR", "Sales", "IT",
                   "HR", "Sales", "IT", "HR", "Sales",
                   "IT", "HR", "Sales", "IT", "HR"],

    "Salary": [45000, 65000, 50000, 55000, 75000,
               48000, 60000, 85000, 52000, 70000,
               90000, 58000, 62000, 80000, 55000],

    "YearsExperience": [2, 6, 8, 5, 10,
                        3, 7, 12, 1, 9,
                        15, 4, 6, 11, 2]
}

In [73]:
df = pd.DataFrame(data)

In [74]:
df

    EmpID Department  Salary  YearsExperience
0     101      Sales   45000                2
1     102         IT   65000                6
2     103         HR   50000                8
3     104      Sales   55000                5
4     105         IT   75000               10
5     106         HR   48000                3
6     107      Sales   60000                7
7     108         IT   85000               12
8     109         HR   52000                1
9     110      Sales   70000                9
10    111         IT   90000               15
11    112         HR   58000                4
12    113      Sales   62000                6
13    114         IT   80000               11
14    115         HR   55000                2

In [77]:
# Filter employees with YearsExperience > 5 and display only EmpID , Department , and Salary .
filtered_exp = df[df["YearsExperience"]>5],["EmpID" , "Department" , "Salary"]

In [78]:
filtered_exp

(    EmpID Department  Salary  YearsExperience
 1     102         IT   65000                6
 2     103         HR   50000                8
 4     105         IT   75000               10
 6     107      Sales   60000                7
 7     108         IT   85000               12
 9     110      Sales   70000                9
 10    111         IT   90000               15
 12    113      Sales   62000                6
 13    114         IT   80000               11,
 ['EmpID', 'Department', 'Salary'])

In [80]:
# Sort the full DataFrame first by Department (ascending) and then by Salary (descending)
sorted_df = df.sort_values(
    by=["Department","Salary"],
    ascending=[True, False]
)

In [81]:
sorted_df

    EmpID Department  Salary  YearsExperience
11    112         HR   58000                4
14    115         HR   55000                2
8     109         HR   52000                1
2     103         HR   50000                8
5     106         HR   48000                3
10    111         IT   90000               15
7     108         IT   85000               12
13    114         IT   80000               11
4     105         IT   75000               10
1     102         IT   65000                6
9     110      Sales   70000                9
12    113      Sales   62000                6
6     107      Sales   60000                7
3     104      Sales   55000                5
0     101      Sales   45000                2

In [87]:
# Use .apply() with a lambda function to create a new column "SeniorityLevel" : "Senior" 
# if experience > 7, "Mid" if 3–7, otherwise "Junior" 
df["SeniorityLevel"] = df["YearsExperience"].apply(lambda x :"Senior" if x > 7 else "Mid" if x >= 3 else "Junior")

In [88]:
df

    EmpID Department  Salary  YearsExperience SeniorityLevel
0     101      Sales   45000                2         Junior
1     102         IT   65000                6            Mid
2     103         HR   50000                8         Senior
3     104      Sales   55000                5            Mid
4     105         IT   75000               10         Senior
5     106         HR   48000                3            Mid
6     107      Sales   60000                7            Mid
7     108         IT   85000               12         Senior
8     109         HR   52000                1         Junior
9     110      Sales   70000                9         Senior
10    111         IT   90000               15         Senior
11    112         HR   58000                4            Mid
12    113      Sales   62000                6            Mid
13    114         IT   80000               11         Senior
14    115         HR   55000                2         Junior

In [89]:
# A DataFrame df of 10 product records contains some missing values in the Price column and a few duplicate rows.
# Detect and count missing values per column.
# Fill missing Price values with the column's median.
# Identify and remove duplicate rows, keeping only the first occurrence.

In [105]:
data = {
    "ProductID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer",
                "Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [80000, 1500, np.nan, 25000, 18000,
              80000, np.nan, 3500, 25000, 18000],
    "Quantity": [5, 20, 15, 8, 10, 5, 20, 12, 8, 10]
}

In [106]:
df = pd.DataFrame(data)

In [107]:
df

   ProductID   Product    Price  Quantity
0        101    Laptop  80000.0         5
1        102     Mouse   1500.0        20
2        103  Keyboard      NaN        15
3        104   Monitor  25000.0         8
4        105   Printer  18000.0        10
5        106    Laptop  80000.0         5
6        107     Mouse      NaN        20
7        108  Keyboard   3500.0        12
8        109   Monitor  25000.0         8
9        110   Printer  18000.0        10

In [108]:
# Detect and count missing values per column.
df.isnull().sum()

ProductID    0
Product      0
Price        2
Quantity     0
dtype: int64

In [109]:
# Fill missing Price values with the column's median.
median_price = df["Price"].median()

In [110]:
df["Price"] = df["Price"].fillna(median_price)

In [111]:
df

   ProductID   Product    Price  Quantity
0        101    Laptop  80000.0         5
1        102     Mouse   1500.0        20
2        103  Keyboard  21500.0        15
3        104   Monitor  25000.0         8
4        105   Printer  18000.0        10
5        106    Laptop  80000.0         5
6        107     Mouse  21500.0        20
7        108  Keyboard   3500.0        12
8        109   Monitor  25000.0         8
9        110   Printer  18000.0        10

In [112]:
# Identify and remove duplicate rows, keeping only the first occurrence
df.duplicated().sum()

np.int64(0)

In [113]:
df = df.drop_duplicates(keep="first")

In [114]:
# df

   ProductID   Product    Price  Quantity
0        101    Laptop  80000.0         5
1        102     Mouse   1500.0        20
2        103  Keyboard  21500.0        15
3        104   Monitor  25000.0         8
4        105   Printer  18000.0        10
5        106    Laptop  80000.0         5
6        107     Mouse  21500.0        20
7        108  Keyboard   3500.0        12
8        109   Monitor  25000.0         8
9        110   Printer  18000.0        10

In [116]:
# A retail company tracks daily temperature (°C) and ice-cream sales (units) for 30 days.
# Using np.random.seed(7) , generate temperature as 30 values drawn from np.random.normal(loc=25, scale=5, size=30) (round to 1 decimal), and sales as np.random.randint(50, 300, size=30) .
# Build a DataFrame with columns ["Day", "Temperature", "Sales"] where Day ranges from 1 to 30.
# Use np.where to create a new column "Weather" : "Hot" if Temperature > 28, "Mild" if between 18 and 28 (inclusive), otherwise "Cold" .
# Set a MultiIndex on ["Weather", "Day"] , then group by Weather to calculate the average Sales for each category.
# Compute the Pearson correlation coefficient between Temperature and Sales using np.corrcoef() , and briefly interpret whether hotter days are associated with higher sales.

In [4]:
np.random.seed(7)

In [9]:
data = np.random.normal(loc=25, scale=5, size=30)

In [10]:
data

array([23.15590766, 15.46815061, 24.50194684, 33.49768648, 23.08288439,
       20.55071569, 19.03204039, 19.74991594, 23.49903132, 19.10008953,
       32.48819558, 23.58682382, 25.54324186, 32.1911976 , 32.5165926 ,
       23.93633516, 26.65987108, 28.67513292, 24.0357227 , 16.10993574,
       28.27352852, 29.47176152, 27.07751307, 20.38227672, 24.01986344,
       22.04615091, 23.50144381, 31.48442596, 32.64789817, 28.34709097])

In [11]:
np.round(data, 1)

array([23.2, 15.5, 24.5, 33.5, 23.1, 20.6, 19. , 19.7, 23.5, 19.1, 32.5,
       23.6, 25.5, 32.2, 32.5, 23.9, 26.7, 28.7, 24. , 16.1, 28.3, 29.5,
       27.1, 20.4, 24. , 22. , 23.5, 31.5, 32.6, 28.3])

In [15]:
sales = np.random.randint(50, 300, size=30)
sales

array([269, 192,  95, 155,  92, 146,  84, 145, 162, 233, 280, 196,  59,
       251,  63, 135, 221,  51,  81, 192, 258,  98, 203, 291, 288, 211,
       263, 261, 132, 114], dtype=int32)

In [17]:
df = pd.DataFrame({
    "Day": range(1, 31),
    "Temperature": data,
    "Sales": sales
})

In [19]:
df.head()

   Day  Temperature  Sales
0    1    23.155908    269
1    2    15.468151    192
2    3    24.501947     95
3    4    33.497686    155
4    5    23.082884     92

In [20]:
df["Weather"] = np.where(df["Temperature"]>28,"Hot", np.where(
        df["Temperature"].between(18, 28),
        "Mild",
        "Cold"
    ))

In [22]:
df.head()

   Day  Temperature  Sales Weather
0    1    23.155908    269    Mild
1    2    15.468151    192    Cold
2    3    24.501947     95    Mild
3    4    33.497686    155     Hot
4    5    23.082884     92    Mild

In [23]:
df = df.set_index(["Weather", "Day"])

In [24]:
df

             Temperature  Sales
Weather Day
Mild    1      23.155908    269
Cold    2      15.468151    192
Mild    3      24.501947     95
Hot     4      33.497686    155
Mild    5      23.082884     92
        6      20.550716    146
        7      19.032040     84
        8      19.749916    145
        9      23.499031    162
        10     19.100090    233
Hot     11     32.488196    280
Mild    12     23.586824    196
        13     25.543242     59
Hot     14     32.191198    251
        15     32.516593     63
Mild    16     23.936335    135
        17     26.659871    221
Hot     18     28.675133     51
Mild    19     24.035723     81
Cold    20     16.109936    192
Hot     21     28.273529    258
        22     29.471762     98
Mild    23     27.077513    203
        24     20.382277    291
        25     24.019863    288
        26     22.046151    211
        27     23.501444    263
Hot     28     31.484426    261
        29     32.647898    132
        30     28.347091    114

In [25]:
# Group by Weather and calculate average Sales
avg_sales = df.groupby(level="Weather")["Sales"].mean()

In [26]:
avg_sales

Weather
Cold    192.000000
Hot     166.300000
Mild    176.333333
Name: Sales, dtype: float64

In [27]:
# Pearson correlation coefficient
correlation_matrix = np.corrcoef(
    df["Temperature"],
    df["Sales"]
)

In [28]:
correlation_matrix

array([[ 1.        , -0.05992086],
       [-0.05992086,  1.        ]])