In [1]:
import numpy as np
import pandas as pd

In [299]:
# wap to add list elements of array belonging to nth index and convert to new list 
l1 = [1,2,3,4,5]
l2 = [4,5,6,6,7]

In [300]:
l3 = []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
print(l3)

[5, 7, 9, 10, 12]

In [301]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [191]:
a+b

array([3, 5, 7, 9])

In [192]:
a-b

array([-1, -1, -1, -1])

In [193]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [194]:
a*2

array([2, 4, 6, 8])

In [195]:
a**2

array([ 1,  4,  9, 16])

In [196]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
np.zeros(2)

array([0., 0.])

In [198]:
np.ones(4)

array([1., 1., 1., 1.])

In [199]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [200]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [201]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [202]:
np.arange(1,16,3)

array([ 1,  4,  7, 10, 13])

In [203]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [204]:
arr = np. array([2,3,4,5,6])

In [205]:
arr

array([2, 3, 4, 5, 6])

In [206]:
arr.shape

(5,)

In [207]:
arr = np. array([[2,3,4,5,6]])

In [208]:
arr

array([[2, 3, 4, 5, 6]])

In [209]:
arr.shape

(1, 5)

In [210]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [211]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [212]:
#row and column
arr.shape

(2, 5)

In [213]:
# number of dimensions
arr.ndim

2

In [214]:
# size of array
arr.size

10

In [215]:
# data type of array
arr.dtype

dtype('int64')

In [216]:
# memory size
arr.itemsize

8

In [217]:
arr1 = np.array([[True,True,False]])

In [218]:
arr1.dtype

dtype('bool')

In [219]:
arr1.itemsize

1

In [220]:
arr2 = np.array([[True,True,"a"]])

In [221]:
arr2.dtype

dtype('<U5')

In [222]:
arr2.itemsize

20

In [223]:
arr2.item

In [224]:
arr = np. array([[1,2,3,4,5],[2,3,4,5,6]])

In [225]:
# indexing and slicing
arr[1]

array([2, 3, 4, 5, 6])

In [226]:
arr[1,2]

np.int64(4)

In [227]:
#start:stop
arr[1:3]

array([[2, 3, 4, 5, 6]])

In [228]:
arr = np. array([[1,2,3,4,5]])

In [229]:
arr[0]

array([1, 2, 3, 4, 5])

In [230]:
arr[:2]

array([[1, 2, 3, 4, 5]])

In [231]:
arr[0:]

array([[1, 2, 3, 4, 5]])

In [232]:
#entire row and fixed column
arr[:,1]

array([2])

In [233]:
#row, column
arr[:,0:2]

array([[1, 2]])

In [234]:
arr = np. array([[1,2],[3,4],[5,6]])

In [235]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [236]:
arr[0:2,:]

array([[1, 2],
       [3, 4]])

In [237]:
arr[1:2,:]

array([[3, 4]])

In [238]:
arr[1:3,:]

array([[3, 4],
       [5, 6]])

In [239]:
arr = np. array([[1,2,9],[3,4,2],[5,6,7]])

In [240]:
arr

array([[1, 2, 9],
       [3, 4, 2],
       [5, 6, 7]])

In [241]:
arr[1:3,1:3]

array([[4, 2],
       [6, 7]])

In [242]:
# mathematical operations
arr1 = np. array([[1,2,9],[3,4,2]])
arr2 = np. array([[3,1,2],[5,6,4]])

In [243]:
arr1+arr2

array([[ 4,  3, 11],
       [ 8, 10,  6]])

In [244]:
arr1-arr2

array([[-2,  1,  7],
       [-2, -2, -2]])

In [245]:
arr1*arr2

array([[ 3,  2, 18],
       [15, 24,  8]])

In [246]:
arr1/arr2

array([[0.33333333, 2.        , 4.5       ],
       [0.6       , 0.66666667, 0.5       ]])

In [247]:
arr1 **2

array([[ 1,  4, 81],
       [ 9, 16,  4]])

In [248]:
# reshaping
arr = np.array([[1,2,3,4]])

In [249]:
arr

array([[1, 2, 3, 4]])

In [250]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [251]:
arr = np.array([[1,2,3,4,2,6,7]])

In [252]:
arr

array([[1, 2, 3, 4, 2, 6, 7]])

In [253]:
arr.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [6],
       [7]])

In [254]:
# practice assignment

In [255]:
# create a Numpy array of integers from  1 to 20 (inclusive).Then:
# 1. Reshape it into a 4×5 array.
# 2. Print its shape, number of dimensions, and total size.
# 3. Extract the second row and the last column separately.

In [256]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [257]:
new_arr = arr.reshape(4,5)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [258]:
new_arr.size

20

In [259]:
new_arr.shape

(4, 5)

In [260]:
new_arr.ndim

2

In [261]:
# Using NumPy's built-in generators (not manual lists):
# 1. Create a 3×3 identity matrix using np.eye() .
# 2. Create an array of 10 evenly spaced values between 0 and 1 using np.linspace() .
# 3. Create a 2×4 array filled entirely with the value 7 using np.full() .

In [262]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [263]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [264]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [265]:
# Create two NumPy arrays: a = np.array([10, 20, 30, 40]) and b = np.array([1, 2, 3, 4]) .
# 1. Compute their element-wise sum, difference, product, and quotient.
# 2. Create a 4×4 matrix by broadcasting a as rows and adding b as a column vector (i.e. a + b.reshape(4,1) ). Print
# the result.
# 3. Explain in one sentence (as a code comment) what broadcasting rule made step 2 possible.

In [266]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [267]:
# sum
a+b

array([11, 22, 33, 44])

In [268]:
# difference
a-b

array([ 9, 18, 27, 36])

In [269]:
# quotient
a/b

array([10., 10., 10., 10.])

In [270]:
# reshape a+b
reshape_result = a+b.reshape(4,1)
reshape_result

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [271]:
# Broadcasting works because the 1D array a is automatically expanded across rows to match b's (4,1) column shape.

In [272]:
# Using np.random.seed(10) , generate arr = np.random.randint(1, 100, size=20) .
# 1. Print all elements greater than 50 using boolean indexing.
# 2. Replace all elements less than 20 with 0 (in place).
# 3. Compute the mean, median, standard deviation, minimum, and maximum of the updated array.

In [273]:
np.random.seed(10)
arr1 = np.random.randint(1, 100, size=20)
print(arr1)

[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79]

In [274]:
print(arr1[arr1 > 50])

[65 90 94 74 55 89 63 73 79]

In [275]:
arr1[arr1<20] = 0
print(arr1)

[ 0  0 65 29 90 94 30  0 74  0 41 37  0  0 55 89 63 34 73 79]

In [276]:
np.mean(arr1)

np.float64(42.65)

In [277]:
np.median(arr1)

np.float64(39.0)

In [278]:
np.std(arr1)

np.float64(33.681263337351226)

In [279]:
np.min(arr1)

np.int32(0)

In [280]:
np.max(arr1)

np.int32(94)

In [281]:
# Create two 3×3 matrices:
# A = np.array([[2, 0, 1], [1, 3, 2], [4, 1, 5]])
# B = np.array([[1, 2, 0], [0, 1, 2], [2, 0, 1]])
# Compute the matrix product A · B using np.dot() or the @ operator (not element-wise multiplication).
# Compute the transpose of A and the determinant of A using np.linalg.det() .
# Check whether A is invertible (based on its determinant), and if so, compute its inverse using np.linalg.inv() .
# Verify your result by multiplying A with its inverse and confirming you get (approximately) the identity matrix.

In [282]:
A = np.array([[2, 0, 1], [1, 3, 2], [4, 1, 5]])
B = np.array([[1, 2, 0], [0, 1, 2], [2, 0, 1]])

In [283]:
np.dot(A,B)

array([[ 4,  4,  1],
       [ 5,  5,  8],
       [14,  9,  7]])

In [284]:
np.transpose(A)

array([[2, 1, 4],
       [0, 3, 1],
       [1, 2, 5]])

In [285]:
np.linalg.det(A)

np.float64(15.000000000000007)

In [292]:
# pandas practice questions

In [302]:
# Create a Pandas Series from the list [45, 78, 23, 90, 56] with custom index labels ["Math", "Science",
# "English", "History", "Art"] .
# 1. Print the value corresponding to "Science" .
# 2. Print all subjects where the score is above 50.
# 3. Sort the Series by value in ascending order.

In [307]:
scores = pd.Series([45, 78, 23, 90, 56],
                  index=["Math", "Science","English", "History", "Art"])

In [308]:
print(scores)

Math       45
Science    78
English    23
History    90
Art        56
dtype: int64

In [313]:
print(scores[scores > 50])

Science    78
History    90
Art        56
dtype: int64

In [314]:
print(scores.sort_values())

English    23
Math       45
Art        56
Science    78
History    90
dtype: int64

In [315]:
print(scores["Science"])

78

In [ ]:
# Assume you have a CSV file named sales_data.csv with columns ["OrderID", "Product", "Quantity",
# "Price", "Date"] .
# 1. Load it into a DataFrame using pd.read_csv() .
# 2. Display the first 5 rows, the last 5 rows, and a summary using .info() .
# 3. Check for and count any missing values in each column using .isnull().sum() .

In [36]:
df = pd.read_excel("Product-Sales-Region.xlsx")

In [37]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [38]:
df.tail()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[us]
 1   Region         1500 non-null   str
 2   Product        1500 non-null   str
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   str
 6   CustomerType   1500 non-null   str
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   str
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   str
 11  Promotion      1130 non-null   str
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   str
 14  CustomerName   1500 non-null   str
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[us]
 17  DeliveryDate   1500 non-null   datetime64[us]
 18  RegionManager  1500 non-null   str
dtypes: datetime64[us](3), float64(4), int64(2), str(10)
memory usage: 222.8 KB

In [40]:
df.isnull()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [41]:
df.isna().sum()

Date               0
Region             0
Product            0
Quantity           0
UnitPrice          0
StoreLocation      0
CustomerType       0
Discount           0
Salesperson        0
TotalPrice         0
PaymentMethod      0
Promotion        370
Returned           0
OrderID            0
CustomerName       0
ShippingCost       0
OrderDate          0
DeliveryDate       0
RegionManager      0
dtype: int64

In [42]:
# Continuing with the sales_data.csv DataFrame from Question 7:
# 1. Drop any rows where Quantity or Price is missing.
# 2. Create a new column "TotalAmount" as Quantity × Price .
# 3. Convert the Date column to datetime format using pd.to_datetime() and extract the month into a new column
# "Month" .

In [43]:
df.dropna(subset=['Quantity','UnitPrice'])

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,REG101495,Cust 5227,35.63,2025-02-17,2025-02-22,Wendy
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,REG101496,Cust 5559,45.93,2024-01-11,2024-01-17,Sophie
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,REG101497,Cust 8981,35.56,2024-07-27,2024-08-03,Eric
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,REG101498,Cust 1824,24.53,2024-12-03,2024-12-10,Cameron
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,REG101499,Cust 1935,21.05,2025-05-09,2025-05-13,Wendy

In [44]:
df['Total Amount'] = df['Quantity']*df['UnitPrice']

In [45]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68

In [46]:
pd.to_datetime(df['Date'])

0      2023-02-23
1      2024-12-19
2      2023-05-10
3      2025-02-26
4      2023-06-24
          ...
1495   2025-02-17
1496   2024-01-11
1497   2024-07-27
1498   2024-12-03
1499   2025-05-09
Name: Date, Length: 1500, dtype: datetime64[us]

In [47]:
df['Month'] = pd.to_datetime(df['Date']).dt.month

In [48]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [49]:
# Using the cleaned DataFrame from Question 8:
# 1. Group the data by Product and calculate the total TotalAmount and average Quantity sold for each product.
# 2. Find the top 3 products by total revenue.
# 3. Group by Month and plot (or print) the total revenue trend across months.

In [50]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [51]:
product_summary = df.groupby('Product').agg(
    Total_Revenue = ('TotalPrice','sum'),
    Average_Quantity = ('Quantity', 'mean')
)

In [52]:
print(product_summary)

         Total_Revenue  Average_Quantity
Product
Chair      622589.4780         10.153110
Desk       555266.6645          9.787440
Laptop     684417.2415         10.654867
Monitor    651629.3925         10.268868
Phone      497162.8510         10.102564
Printer    684387.4155         11.071090
Tablet     684539.3855         10.737500

In [58]:
top3_product = product_summary.sort_values(
    'Total_Revenue',
    ascending=False
).head(3)

In [59]:
print(top3_product)

         Total_Revenue  Average_Quantity
Product
Tablet     684539.3855         10.737500
Laptop     684417.2415         10.654867
Printer    684387.4155         11.071090

In [60]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,Total Amount,Month
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,12
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,5
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,2
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,6

In [62]:
Monthly_revenue = df.groupby('Month')['TotalPrice'].sum()

In [63]:
print(Monthly_revenue)

Month
1     498358.5015
2     415057.8135
3     532090.9535
4     443318.7265
5     402408.0255
6     434261.6690
7     280050.0475
8     289639.0035
9     282114.6490
10    256612.8970
11    283330.6200
12    262749.5220
Name: TotalPrice, dtype: float64

In [65]:
# You have two DataFrames:

# Merge orders and customers on CustomerID using an inner join.
# Create a pivot table showing total Amount spent per City .
# Identify the customer with the highest total spending and print their name and city.

In [73]:
orders = pd.DataFrame({
    "OrderID": [1, 2, 3, 4, 5],
    "CustomerID": [101, 102, 101, 103, 102],
    "Amount": [250, 450, 300, 600, 150]
})
customers = pd.DataFrame({
    "CustomerID": [101, 102, 103],
    "Name": ["Sita", "Ramesh", "Gita"],
    "City": ["Kathmandu", "Pokhara", "Lalitpur"]
})

In [74]:
df= pd.merge(
    orders,
    customers,
    on='CustomerID',
    how='inner'
)

In [78]:
df

   OrderID  CustomerID  Amount    Name       City
0        1         101     250    Sita  Kathmandu
1        2         102     450  Ramesh    Pokhara
2        3         101     300    Sita  Kathmandu
3        4         103     600    Gita   Lalitpur
4        5         102     150  Ramesh    Pokhara

In [79]:
pd.pivot_table(df,values='Amount', index='City', aggfunc='sum')

           Amount
City
Kathmandu     550
Lalitpur      600
Pokhara       600

In [89]:
df

   OrderID  CustomerID  Amount    Name       City
0        1         101     250    Sita  Kathmandu
1        2         102     450  Ramesh    Pokhara
2        3         101     300    Sita  Kathmandu
3        4         103     600    Gita   Lalitpur
4        5         102     150  Ramesh    Pokhara

In [98]:
df.groupby(['Name','City'])['Amount'].sum()

Name    City
Gita    Lalitpur     600
Ramesh  Pokhara      600
Sita    Kathmandu    550
Name: Amount, dtype: int64

In [99]:
# Create a DataFrame from the following dictionary of student data:

# Display the column names, index, and data types.
# Select and print only the Name and Marks columns.
# Select the row for "Chirag" using both .loc and .iloc .

In [102]:
data = {
"Name": ["Aarav", "Bina", "Chirag", "Divya", "Esha"],
"Age": [21, 22, 20, 23, 21],
"Marks": [85, 62, 90, 75, 68]
}

In [111]:
df = pd.DataFrame(data)

In [112]:
df

     Name  Age  Marks
0   Aarav   21     85
1    Bina   22     62
2  Chirag   20     90
3   Divya   23     75
4    Esha   21     68

In [118]:
df[['Name','Marks']]

     Name  Marks
0   Aarav     85
1    Bina     62
2  Chirag     90
3   Divya     75
4    Esha     68

In [115]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [116]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [117]:
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [128]:
# df.loc[2]
df.loc[2:2]

     Name  Age  Marks
2  Chirag   20     90

In [124]:
df.iloc[2:3]

     Name  Age  Marks
2  Chirag   20     90