In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('Product-Sales-Region.xlsx')

In [3]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [4]:
df.shape

(1500, 19)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1500 non-null   datetime64[us]
 1   Region         1500 non-null   str
 2   Product        1500 non-null   str
 3   Quantity       1500 non-null   int64
 4   UnitPrice      1500 non-null   float64
 5   StoreLocation  1500 non-null   str
 6   CustomerType   1500 non-null   str
 7   Discount       1500 non-null   float64
 8   Salesperson    1500 non-null   str
 9   TotalPrice     1500 non-null   float64
 10  PaymentMethod  1500 non-null   str
 11  Promotion      1130 non-null   str
 12  Returned       1500 non-null   int64
 13  OrderID        1500 non-null   str
 14  CustomerName   1500 non-null   str
 15  ShippingCost   1500 non-null   float64
 16  OrderDate      1500 non-null   datetime64[us]
 17  DeliveryDate   1500 non-null   datetime64[us]
 18  RegionManager  1500 non-null   str
dtypes: datetime64[us](3), float64(4), int64(2), str(10)
memory usage: 222.8 KB

In [6]:
df['product_total_price'] = df['Quantity']*df['UnitPrice']

In [7]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,product_total_price
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68

In [8]:
df['revenue'] = df['product_total_price']-df['Discount']-df['ShippingCost']

In [9]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Promotion,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,product_total_price,revenue
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2247.06
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,538.71
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,4825.96
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,6898.66
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,4273.95

In [10]:
df['revenue_in_rupees']=df['revenue']*150.34

In [11]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,...,Returned,OrderID,CustomerName,ShippingCost,OrderDate,DeliveryDate,RegionManager,product_total_price,revenue,revenue_in_rupees
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,...,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric,2290.40,2247.06,3.378230e+05
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,...,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie,544.01,538.71,8.098966e+04
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,...,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan,4846.52,4825.96,7.255348e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,...,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron,6926.76,6898.66,1.037145e+06
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,...,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric,4279.68,4273.95,6.425456e+05

In [12]:
df.drop(columns=['OrderID','CustomerName'], inplace=True)

In [13]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,RegionManager,product_total_price,revenue,revenue_in_rupees
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,43.34,2023-02-23,2023-02-27,Eric,2290.40,2247.06,3.378230e+05
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,5.30,2024-12-19,2024-12-28,Sophie,544.01,538.71,8.098966e+04
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,20.46,2023-05-10,2023-05-19,Ryan,4846.52,4825.96,7.255348e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,27.95,2025-02-26,2025-03-02,Cameron,6926.76,6898.66,1.037145e+06
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,5.73,2023-06-24,2023-06-27,Eric,4279.68,4273.95,6.425456e+05

In [14]:
del(df['RegionManager'])

In [15]:
df.head()

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,43.34,2023-02-23,2023-02-27,2290.40,2247.06,3.378230e+05
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,5.30,2024-12-19,2024-12-28,544.01,538.71,8.098966e+04
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,20.46,2023-05-10,2023-05-19,4846.52,4825.96,7.255348e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,27.95,2025-02-26,2025-03-02,6926.76,6898.66,1.037145e+06
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,5.73,2023-06-24,2023-06-27,4279.68,4273.95,6.425456e+05

In [16]:
df.drop(index=0)

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,5.30,2024-12-19,2024-12-28,544.01,538.71,8.098966e+04
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,20.46,2023-05-10,2023-05-19,4846.52,4825.96,7.255348e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,27.95,2025-02-26,2025-03-02,6926.76,6898.66,1.037145e+06
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,5.73,2023-06-24,2023-06-27,4279.68,4273.95,6.425456e+05
5,2024-02-20,Central,Monitor,2,385.09,Store D,Wholesale,0.15,Diana,654.653,Credit Card,NaN,0,11.92,2024-02-20,2024-03-01,770.18,758.11,1.139743e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,35.63,2025-02-17,2025-02-22,1749.28,1713.60,2.576226e+05
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,45.93,2024-01-11,2024-01-17,3775.50,3729.42,5.606810e+05
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,35.56,2024-07-27,2024-08-03,272.50,236.94,3.562156e+04
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,24.53,2024-12-03,2024-12-10,3677.38,3652.80,5.491620e+05
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,21.05,2025-05-09,2025-05-13,2878.07,2857.02,4.295244e+05

In [17]:
df.drop(index=[1,2])

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.400,Online,FREESHIP,0,43.34,2023-02-23,2023-02-27,2290.40,2247.06,3.378230e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,27.95,2025-02-26,2025-03-02,6926.76,6898.66,1.037145e+06
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.680,Online,SAVE10,0,5.73,2023-06-24,2023-06-27,4279.68,4273.95,6.425456e+05
5,2024-02-20,Central,Monitor,2,385.09,Store D,Wholesale,0.15,Diana,654.653,Credit Card,NaN,0,11.92,2024-02-20,2024-03-01,770.18,758.11,1.139743e+05
6,2023-01-11,South,Chair,7,17.50,Store C,Retail,0.10,Alice,110.250,Debit Card,WINTER15,0,5.02,2023-01-11,2023-01-14,122.50,117.38,1.764691e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2025-02-17,West,Desk,13,134.56,Store D,Retail,0.05,Carlos,1661.816,Credit Card,WINTER15,0,35.63,2025-02-17,2025-02-22,1749.28,1713.60,2.576226e+05
1496,2024-01-11,South,Chair,18,209.75,Store C,Wholesale,0.15,Frank,3209.175,Debit Card,FREESHIP,0,45.93,2024-01-11,2024-01-17,3775.50,3729.42,5.606810e+05
1497,2024-07-27,East,Desk,1,272.50,Store A,Wholesale,0.00,Eva,272.500,Gift Card,WINTER15,0,35.56,2024-07-27,2024-08-03,272.50,236.94,3.562156e+04
1498,2024-12-03,Central,Monitor,14,262.67,Store A,Retail,0.05,Carlos,3493.511,Gift Card,SAVE10,0,24.53,2024-12-03,2024-12-10,3677.38,3652.80,5.491620e+05
1499,2025-05-09,West,Chair,13,221.39,Store D,Wholesale,0.00,Frank,2878.070,Debit Card,FREESHIP,1,21.05,2025-05-09,2025-05-13,2878.07,2857.02,4.295244e+05

In [18]:
df.dtypes

Date                   datetime64[us]
Region                            str
Product                           str
Quantity                        int64
UnitPrice                     float64
StoreLocation                     str
CustomerType                      str
Discount                      float64
Salesperson                       str
TotalPrice                    float64
PaymentMethod                     str
Promotion                         str
Returned                        int64
ShippingCost                  float64
OrderDate              datetime64[us]
DeliveryDate           datetime64[us]
product_total_price           float64
revenue                       float64
revenue_in_rupees             float64
dtype: object

In [19]:
# df['UnitPrice'] = df['UnitPrice'].astype(str)
# df['Quantity'] = df['Quantity'].astype(str)

In [20]:
# df.dtypes

In [21]:
df.describe()

,Date,Quantity,UnitPrice,Discount,TotalPrice,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
count,1500,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500,1500,1500.000000,1500.000000,1.500000e+03
mean,2024-04-07 21:35:02.400000,10.410667,298.826947,0.073133,2919.994952,0.248000,27.507293,2024-04-07 21:35:02.400000,2024-04-13 22:36:28.800000,3151.928627,3124.348200,4.697145e+05
min,2023-01-01 00:00:00,1.000000,5.520000,0.000000,6.970000,0.000000,5.010000,2023-01-01 00:00:00,2023-01-08 00:00:00,8.200000,-34.960000,-5.255886e+03
25%,2023-08-20 00:00:00,5.000000,151.020000,0.000000,867.136250,0.000000,16.700000,2023-08-20 00:00:00,2023-08-25 12:00:00,917.250000,894.407500,1.344652e+05
50%,2024-04-08 12:00:00,11.000000,294.740000,0.050000,2174.724000,0.000000,27.100000,2024-04-08 12:00:00,2024-04-15 12:00:00,2348.315000,2322.300000,3.491346e+05
75%,2024-12-07 06:00:00,15.000000,446.702500,0.100000,4414.723500,0.000000,38.635000,2024-12-07 06:00:00,2024-12-13 06:00:00,4747.322500,4725.862500,7.104862e+05
max,2025-06-30 00:00:00,20.000000,599.720000,0.150000,11077.000000,1.000000,49.980000,2025-06-30 00:00:00,2025-07-10 00:00:00,11526.000000,11500.730000,1.729020e+06
std,NaN,5.735732,169.100075,0.055979,2522.789977,0.431996,13.093453,NaN,NaN,2712.312065,2712.473904,4.077933e+05

In [22]:
df[['UnitPrice','TotalPrice']].describe()

         UnitPrice    TotalPrice
count  1500.000000   1500.000000
mean    298.826947   2919.994952
std     169.100075   2522.789977
min       5.520000      6.970000
25%     151.020000    867.136250
50%     294.740000   2174.724000
75%     446.702500   4414.723500
max     599.720000  11077.000000

In [29]:
df.loc[1:3]

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.010,Gift Card,SAVE10,0,5.30,2024-12-19,2024-12-28,544.01,538.71,8.098966e+04
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.868,Online,WINTER15,0,20.46,2023-05-10,2023-05-19,4846.52,4825.96,7.255348e+05
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.746,Gift Card,FREESHIP,0,27.95,2025-02-26,2025-03-02,6926.76,6898.66,1.037145e+06

In [30]:
df.loc[2,'Product']

'Desk'

In [33]:
df.iloc[2,2]

'Desk'

In [34]:
df.loc[2,'UnitPrice']

np.float64(346.18)

In [35]:
df.iloc[2,4]

np.float64(346.18)

In [37]:
df[df['Promotion'].isnull()]

,Date,Region,Product,Quantity,UnitPrice,StoreLocation,CustomerType,Discount,Salesperson,TotalPrice,PaymentMethod,Promotion,Returned,ShippingCost,OrderDate,DeliveryDate,product_total_price,revenue,revenue_in_rupees
5,2024-02-20,Central,Monitor,2,385.09,Store D,Wholesale,0.15,Diana,654.6530,Credit Card,NaN,0,11.92,2024-02-20,2024-03-01,770.18,758.11,1.139743e+05
7,2023-01-09,Central,Chair,3,330.22,Store C,Wholesale,0.15,Carlos,842.0610,Cash,NaN,0,48.01,2023-01-09,2023-01-11,990.66,942.50,1.416955e+05
10,2024-04-10,North,Desk,15,523.29,Store B,Wholesale,0.15,Eva,6671.9475,Debit Card,NaN,0,12.14,2024-04-10,2024-04-17,7849.35,7837.06,1.178224e+06
11,2024-07-12,East,Phone,19,207.35,Store D,Retail,0.10,Eva,3545.6850,Gift Card,NaN,1,44.89,2024-07-12,2024-07-18,3939.65,3894.66,5.855232e+05
13,2025-01-18,West,Tablet,1,157.83,Store A,Wholesale,0.15,Carlos,134.1555,Debit Card,NaN,0,42.82,2025-01-18,2025-01-22,157.83,114.86,1.726805e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,2023-12-17,South,Monitor,9,55.04,Store B,Retail,0.15,Alice,421.0560,Online,NaN,0,31.09,2023-12-17,2023-12-23,495.36,464.12,6.977580e+04
1472,2025-06-30,South,Phone,20,444.77,Store B,Wholesale,0.10,Diana,8005.8600,Online,NaN,1,20.05,2025-06-30,2025-07-07,8895.40,8875.25,1.334305e+06
1480,2024-08-16,West,Printer,16,483.37,Store B,Retail,0.10,Alice,6960.5280,Debit Card,NaN,0,42.52,2024-08-16,2024-08-22,7733.92,7691.30,1.156310e+06
1481,2025-05-30,North,Monitor,6,159.53,Store A,Retail,0.05,Bob,909.3210,Gift Card,NaN,0,48.60,2025-05-30,2025-06-07,957.18,908.53,1.365884e+05
1489,2024-11-27,South,Phone,13,196.80,Store B,Retail,0.10,Diana,2302.5600,Cash,NaN,0,10.12,2024-11-27,2024-12-07,2558.40,2548.18,3.830934e+05

In [40]:
df['Promotion'] = df['Promotion'].fillna('NOT_APPLICABLE')

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1500 non-null   datetime64[us]
 1   Region               1500 non-null   str
 2   Product              1500 non-null   str
 3   Quantity             1500 non-null   int64
 4   UnitPrice            1500 non-null   float64
 5   StoreLocation        1500 non-null   str
 6   CustomerType         1500 non-null   str
 7   Discount             1500 non-null   float64
 8   Salesperson          1500 non-null   str
 9   TotalPrice           1500 non-null   float64
 10  PaymentMethod        1500 non-null   str
 11  Promotion            1500 non-null   str
 12  Returned             1500 non-null   int64
 13  ShippingCost         1500 non-null   float64
 14  OrderDate            1500 non-null   datetime64[us]
 15  DeliveryDate         1500 non-null   datetime64[us]
 16  product_total_price  1500 non-null   float64
 17  revenue              1500 non-null   float64
 18  revenue_in_rupees    1500 non-null   float64
dtypes: datetime64[us](3), float64(7), int64(2), str(7)
memory usage: 222.8 KB