In [117]:
import pandas as pd
import numpy as np

In [118]:
var = pd.DataFrame(
    [
        [1,2,3,4,5],
        ['a','b','c','d','e']
    ]
)

In [119]:
print(var)

   0  1  2  3  4
0  1  2  3  4  5
1  a  b  c  d  e

In [120]:
var.shape

(2, 5)

In [121]:
var.columns = ['c1','c2','c3','c4','c5']

In [122]:
var

  c1 c2 c3 c4 c5
0  1  2  3  4  5
1  a  b  c  d  e

In [123]:
var.index = ['A','B']

In [124]:
var

  c1 c2 c3 c4 c5
A  1  2  3  4  5
B  a  b  c  d  e

In [125]:
var.rename(columns={'c5':'col5'})

  c1 c2 c3 c4 col5
A  1  2  3  4    5
B  a  b  c  d    e

In [126]:
var.rename(index={'B':'row2'})

     c1 c2 c3 c4 c5
A     1  2  3  4  5
row2  a  b  c  d  e

In [127]:
stu_details = {
     "name":['Hem','Rajan','Mahesh'],
     "age":[23,21,22],
     "address":['KTM','Dhn','Mnr']
    }

In [128]:
df = pd.DataFrame(stu_details)

In [129]:
df

     name  age address
0     Hem   23     KTM
1   Rajan   21     Dhn
2  Mahesh   22     Mnr

In [130]:
df.columns = ['Name','Age','Address']   #to change the column name

In [131]:
df

     Name  Age Address
0     Hem   23     KTM
1   Rajan   21     Dhn
2  Mahesh   22     Mnr

In [132]:
df.index = ['R1','R2','R3']   #to change the index(Row) name

In [133]:
df

      Name  Age Address
R1     Hem   23     KTM
R2   Rajan   21     Dhn
R3  Mahesh   22     Mnr

In [134]:
df.rename(columns={"Name":"Stu-Name"})   #fixed column name change

   Stu-Name  Age Address
R1      Hem   23     KTM
R2    Rajan   21     Dhn
R3   Mahesh   22     Mnr

In [135]:
df.rename(index={'R1':'Row1'})  #fixed index name change

        Name  Age Address
Row1     Hem   23     KTM
R2     Rajan   21     Dhn
R3    Mahesh   22     Mnr

In [136]:
df

      Name  Age Address
R1     Hem   23     KTM
R2   Rajan   21     Dhn
R3  Mahesh   22     Mnr

In [137]:
marks = pd.Series([12,23,43,45])  #creates a series

In [138]:
marks

0    12
1    23
2    43
3    45
dtype: int64

In [139]:
# reading data from the file

In [140]:
# reading csv file
df = pd.read_csv('annual-ent.csv')

In [141]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [142]:
df.head()   #first five row data

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [143]:
df.tail()  #last 5 rows

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [144]:
df.shape  #(rows, columns)

(60255, 10)

In [145]:
df.columns #columns name

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='str')

In [146]:
df.index #index

RangeIndex(start=0, stop=60255, step=1)

In [147]:
df.info()  #summary of dataframe

<class 'pandas.DataFrame'>
RangeIndex: 60255 entries, 0 to 60254
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         60255 non-null  int64
 1   Industry_aggregation_NZSIOC  60255 non-null  str
 2   Industry_code_NZSIOC         60255 non-null  str
 3   Industry_name_NZSIOC         60255 non-null  str
 4   Units                        60255 non-null  str
 5   Variable_code                60255 non-null  str
 6   Variable_name                60255 non-null  str
 7   Variable_category            60255 non-null  str
 8   Value                        60255 non-null  str
 9   Industry_code_ANZSIC06       60255 non-null  str
dtypes: int64(1), str(9)
memory usage: 4.6 MB

In [148]:
df['Year']  #selecting single column

0        2025
1        2025
2        2025
3        2025
4        2025
         ...
60250    2013
60251    2013
60252    2013
60253    2013
60254    2013
Name: Year, Length: 60255, dtype: int64

In [149]:
df[['Year','Units']]  #selecting multiple columns

       Year               Units
0      2025  Dollars (millions)
1      2025  Dollars (millions)
2      2025  Dollars (millions)
3      2025  Dollars (millions)
4      2025  Dollars (millions)
...     ...                 ...
60250  2013          Percentage
60251  2013          Percentage
60252  2013          Percentage
60253  2013          Percentage
60254  2013          Percentage

[60255 rows x 2 columns]

In [150]:
# selecting rows

In [151]:
df.loc[0]

Year                                                                        2025
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     976077
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [152]:
df.loc[0:4]   #selecting multiple rows

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [153]:
df.loc[2:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [154]:
df.loc[2:4,["Year","Variable_code"]]   #row and column selection

   Year Variable_code
2  2025           H05
3  2025           H07
4  2025           H08

In [155]:
# Position-based selection
df.iloc

In [156]:
df.iloc[0:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...

In [157]:
df.iloc[1,3]  #selecting cell using row and column index

'All industries'

In [158]:
data = {
    'A':[12,13,14],
    'B':(10,20,30),
}

In [159]:
pd.DataFrame(data)

    A   B
0  12  10
1  13  20
2  14  30

In [160]:
data1 = [
    {1,2,3,4},
    {10,11,12,13},
    {21,22,23,24}
]

In [161]:
pd.DataFrame(data1)

    0   1   2   3
0   1   2   3   4
1  10  11  12  13
2  24  21  22  23

In [162]:
data1 = [
    {'name':'Hem', 'age':23},
    {'name':'Raj','age':21},
    {'name':'Ramesh','age':45}
]

In [163]:
pd.DataFrame(data1)

     name  age
0     Hem   23
1     Raj   21
2  Ramesh   45

In [164]:
data1

[{'name': 'Hem', 'age': 23},
 {'name': 'Raj', 'age': 21},
 {'name': 'Ramesh', 'age': 45}]

In [165]:
# reading csv file
df = pd.read_csv('loan_approval_nepal_clean.csv')

In [166]:
df

,name,age,monthly_income_npr,credit_score,existing_loans,loan_status
0,Rajesh Shrestha,31,105904,846,0,Approved
1,Maya Gurung,37,50454,341,1,Rejected
2,Bishnu Thapa,26,137009,300,3,Approved
3,Sunita Karki,57,44916,484,2,Rejected
4,Dinesh Rai,56,83911,301,3,Rejected
5,Kamala Poudel,32,84637,634,3,Approved
6,Ramesh Bhandari,30,35139,336,1,Rejected
7,Gita Tamang,58,62861,559,1,Rejected
8,Suresh Adhikari,42,30712,801,1,Approved
9,Radha Chhetri,42,32028,563,2,Rejected
10,Mohan Basnet,34,91850,644,3,Approved
11,Sarita Magar,27,137512,481,3,Approved
12,Hari Bhattarai,59,32635,655,0,Rejected
13,Laxmi Lama,40,78003,394,2,Rejected
14,Krishna Yadav,28,102201,822,0,Approved
15,Parbati Khadka,56,32142,777,1,Approved
16,Naresh Bista,27,61624,451,1,Rejected
17,Kabita Ghimire,38,69047,599,1,Approved
18,Ganesh Regmi,57,132078,650,2,Approved
19,Sabina Rana,49,75746,591,2,Approved
20,Bhim Neupane,55,55669,526,1,Rejected
21,Devi Dahal,34,62449,510,2,Rejected
22,Santosh Pandey,40,28649,390,1,Rejected
23,Pramila Malla,37,83094,604,3,Approved
24,Ram Bhandari,28,80603,702,3,Approved
25,Sushma Subedi,42,42137,414,1,Rejected
26,Keshav Acharya,48,48345,570,3,Rejected
27,Indira Joshi,50,76985,454,3,Rejected
28,Bikram Kandel,31,111523,568,0,Approved
29,Nirmala Baral,38,19342,502,1,Rejected
30,Kishor Katuwal,22,52621,538,3,Rejected
31,Anita Sapkota,27,61263,605,3,Approved
32,Rajan Dhital,27,48509,559,1,Rejected
33,Meena Devkota,57,41749,703,1,Approved
34,Kumar Bhusal,26,98913,783,0,Approved
35,Sabitri Paudel,34,16309,654,2,Rejected
36,Yubraj Koirala,52,23299,467,3,Rejected
37,Sita Ojha,52,120054,300,3,Rejected
38,Prem Bogati,34,131654,550,1,Approved
39,Kalpana Aryal,47,81908,497,2,Approved
40,Tika Rimal,54,31792,599,1,Rejected
41,Uma Bhusal,48,132441,493,2,Approved
42,Dilip Bhandari,54,46017,641,0,Rejected
43,Champa Dhungana,47,136601,793,2,Approved
44,Khem Wagle,37,120552,598,1,Approved
45,Sarala Chapagain,24,86147,707,2,Approved
46,Bal Gautam,29,55125,814,2,Approved
47,Purnima Nepal,55,20240,420,1,Rejected
48,Ashok Rijal,30,27868,665,0,Rejected
49,Hema Poudyal,52,31528,774,3,Approved

In [167]:
df.head()

,name,age,monthly_income_npr,credit_score,existing_loans,loan_status
0,Rajesh Shrestha,31,105904,846,0,Approved
1,Maya Gurung,37,50454,341,1,Rejected
2,Bishnu Thapa,26,137009,300,3,Approved
3,Sunita Karki,57,44916,484,2,Rejected
4,Dinesh Rai,56,83911,301,3,Rejected

In [168]:
df.tail()

,name,age,monthly_income_npr,credit_score,existing_loans,loan_status
45,Sarala Chapagain,24,86147,707,2,Approved
46,Bal Gautam,29,55125,814,2,Approved
47,Purnima Nepal,55,20240,420,1,Rejected
48,Ashok Rijal,30,27868,665,0,Rejected
49,Hema Poudyal,52,31528,774,3,Approved

In [169]:
df[['name','age']]

                name  age
0    Rajesh Shrestha   31
1        Maya Gurung   37
2       Bishnu Thapa   26
3       Sunita Karki   57
4         Dinesh Rai   56
5      Kamala Poudel   32
6    Ramesh Bhandari   30
7        Gita Tamang   58
8    Suresh Adhikari   42
9      Radha Chhetri   42
10      Mohan Basnet   34
11      Sarita Magar   27
12    Hari Bhattarai   59
13        Laxmi Lama   40
14     Krishna Yadav   28
15    Parbati Khadka   56
16      Naresh Bista   27
17    Kabita Ghimire   38
18      Ganesh Regmi   57
19       Sabina Rana   49
20      Bhim Neupane   55
21        Devi Dahal   34
22    Santosh Pandey   40
23     Pramila Malla   37
24      Ram Bhandari   28
25     Sushma Subedi   42
26    Keshav Acharya   48
27      Indira Joshi   50
28     Bikram Kandel   31
29     Nirmala Baral   38
30    Kishor Katuwal   22
31     Anita Sapkota   27
32      Rajan Dhital   27
33     Meena Devkota   57
34      Kumar Bhusal   26
35    Sabitri Paudel   34
36    Yubraj Koirala   52
37         Sita Ojha   52
38       Prem Bogati   34
39     Kalpana Aryal   47
40        Tika Rimal   54
41        Uma Bhusal   48
42    Dilip Bhandari   54
43   Champa Dhungana   47
44        Khem Wagle   37
45  Sarala Chapagain   24
46        Bal Gautam   29
47     Purnima Nepal   55
48       Ashok Rijal   30
49      Hema Poudyal   52

In [170]:
df.shape

(50, 6)

In [171]:
print(df.columns)

Index(['name', 'age', 'monthly_income_npr', 'credit_score', 'existing_loans',
       'loan_status'],
      dtype='str')

In [172]:
df.columns.to_list()

['name',
 'age',
 'monthly_income_npr',
 'credit_score',
 'existing_loans',
 'loan_status']

In [173]:
len(df.columns)

6

In [174]:
df.head()['name']

0    Rajesh Shrestha
1        Maya Gurung
2       Bishnu Thapa
3       Sunita Karki
4         Dinesh Rai
Name: name, dtype: str

In [175]:
# problem statement
# convert monthly_income_npr into usd and create one new column with dollar as price

In [176]:
df['usd_dollar'] = df['monthly_income_npr']/153
df

,name,age,monthly_income_npr,credit_score,existing_loans,loan_status,usd_dollar
0,Rajesh Shrestha,31,105904,846,0,Approved,692.183007
1,Maya Gurung,37,50454,341,1,Rejected,329.764706
2,Bishnu Thapa,26,137009,300,3,Approved,895.483660
3,Sunita Karki,57,44916,484,2,Rejected,293.568627
4,Dinesh Rai,56,83911,301,3,Rejected,548.437908
5,Kamala Poudel,32,84637,634,3,Approved,553.183007
6,Ramesh Bhandari,30,35139,336,1,Rejected,229.666667
7,Gita Tamang,58,62861,559,1,Rejected,410.856209
8,Suresh Adhikari,42,30712,801,1,Approved,200.732026
9,Radha Chhetri,42,32028,563,2,Rejected,209.333333
10,Mohan Basnet,34,91850,644,3,Approved,600.326797
11,Sarita Magar,27,137512,481,3,Approved,898.771242
12,Hari Bhattarai,59,32635,655,0,Rejected,213.300654
13,Laxmi Lama,40,78003,394,2,Rejected,509.823529
14,Krishna Yadav,28,102201,822,0,Approved,667.980392
15,Parbati Khadka,56,32142,777,1,Approved,210.078431
16,Naresh Bista,27,61624,451,1,Rejected,402.771242
17,Kabita Ghimire,38,69047,599,1,Approved,451.287582
18,Ganesh Regmi,57,132078,650,2,Approved,863.254902
19,Sabina Rana,49,75746,591,2,Approved,495.071895
20,Bhim Neupane,55,55669,526,1,Rejected,363.849673
21,Devi Dahal,34,62449,510,2,Rejected,408.163399
22,Santosh Pandey,40,28649,390,1,Rejected,187.248366
23,Pramila Malla,37,83094,604,3,Approved,543.098039
24,Ram Bhandari,28,80603,702,3,Approved,526.816993
25,Sushma Subedi,42,42137,414,1,Rejected,275.405229
26,Keshav Acharya,48,48345,570,3,Rejected,315.980392
27,Indira Joshi,50,76985,454,3,Rejected,503.169935
28,Bikram Kandel,31,111523,568,0,Approved,728.908497
29,Nirmala Baral,38,19342,502,1,Rejected,126.418301
30,Kishor Katuwal,22,52621,538,3,Rejected,343.928105
31,Anita Sapkota,27,61263,605,3,Approved,400.411765
32,Rajan Dhital,27,48509,559,1,Rejected,317.052288
33,Meena Devkota,57,41749,703,1,Approved,272.869281
34,Kumar Bhusal,26,98913,783,0,Approved,646.490196
35,Sabitri Paudel,34,16309,654,2,Rejected,106.594771
36,Yubraj Koirala,52,23299,467,3,Rejected,152.281046
37,Sita Ojha,52,120054,300,3,Rejected,784.666667
38,Prem Bogati,34,131654,550,1,Approved,860.483660
39,Kalpana Aryal,47,81908,497,2,Approved,535.346405
40,Tika Rimal,54,31792,599,1,Rejected,207.790850
41,Uma Bhusal,48,132441,493,2,Approved,865.627451
42,Dilip Bhandari,54,46017,641,0,Rejected,300.764706
43,Champa Dhungana,47,136601,793,2,Approved,892.816993
44,Khem Wagle,37,120552,598,1,Approved,787.921569
45,Sarala Chapagain,24,86147,707,2,Approved,563.052288
46,Bal Gautam,29,55125,814,2,Approved,360.294118
47,Purnima Nepal,55,20240,420,1,Rejected,132.287582
48,Ashok Rijal,30,27868,665,0,Rejected,182.143791
49,Hema Poudyal,52,31528,774,3,Approved,206.065359

In [188]:
# df['n'] = df['name'].apply(lambda y: y.split(':')[0] )
# df['n']

In [179]:
name = df['name'].str.split()

In [180]:
df[['firstname', 'lastname']] = df['name'].str.split(' ', n=1, expand=True)

In [181]:
df

,name,age,monthly_income_npr,credit_score,existing_loans,loan_status,usd_dollar,reason,firstname,lastname
0,Rajesh Shrestha,31,105904,846,0,Approved,692.183007,Rajesh Shrestha,Rajesh,Shrestha
1,Maya Gurung,37,50454,341,1,Rejected,329.764706,Maya Gurung,Maya,Gurung
2,Bishnu Thapa,26,137009,300,3,Approved,895.483660,Bishnu Thapa,Bishnu,Thapa
3,Sunita Karki,57,44916,484,2,Rejected,293.568627,Sunita Karki,Sunita,Karki
4,Dinesh Rai,56,83911,301,3,Rejected,548.437908,Dinesh Rai,Dinesh,Rai
5,Kamala Poudel,32,84637,634,3,Approved,553.183007,Kamala Poudel,Kamala,Poudel
6,Ramesh Bhandari,30,35139,336,1,Rejected,229.666667,Ramesh Bhandari,Ramesh,Bhandari
7,Gita Tamang,58,62861,559,1,Rejected,410.856209,Gita Tamang,Gita,Tamang
8,Suresh Adhikari,42,30712,801,1,Approved,200.732026,Suresh Adhikari,Suresh,Adhikari
9,Radha Chhetri,42,32028,563,2,Rejected,209.333333,Radha Chhetri,Radha,Chhetri
10,Mohan Basnet,34,91850,644,3,Approved,600.326797,Mohan Basnet,Mohan,Basnet
11,Sarita Magar,27,137512,481,3,Approved,898.771242,Sarita Magar,Sarita,Magar
12,Hari Bhattarai,59,32635,655,0,Rejected,213.300654,Hari Bhattarai,Hari,Bhattarai
13,Laxmi Lama,40,78003,394,2,Rejected,509.823529,Laxmi Lama,Laxmi,Lama
14,Krishna Yadav,28,102201,822,0,Approved,667.980392,Krishna Yadav,Krishna,Yadav
15,Parbati Khadka,56,32142,777,1,Approved,210.078431,Parbati Khadka,Parbati,Khadka
16,Naresh Bista,27,61624,451,1,Rejected,402.771242,Naresh Bista,Naresh,Bista
17,Kabita Ghimire,38,69047,599,1,Approved,451.287582,Kabita Ghimire,Kabita,Ghimire
18,Ganesh Regmi,57,132078,650,2,Approved,863.254902,Ganesh Regmi,Ganesh,Regmi
19,Sabina Rana,49,75746,591,2,Approved,495.071895,Sabina Rana,Sabina,Rana
20,Bhim Neupane,55,55669,526,1,Rejected,363.849673,Bhim Neupane,Bhim,Neupane
21,Devi Dahal,34,62449,510,2,Rejected,408.163399,Devi Dahal,Devi,Dahal
22,Santosh Pandey,40,28649,390,1,Rejected,187.248366,Santosh Pandey,Santosh,Pandey
23,Pramila Malla,37,83094,604,3,Approved,543.098039,Pramila Malla,Pramila,Malla
24,Ram Bhandari,28,80603,702,3,Approved,526.816993,Ram Bhandari,Ram,Bhandari
25,Sushma Subedi,42,42137,414,1,Rejected,275.405229,Sushma Subedi,Sushma,Subedi
26,Keshav Acharya,48,48345,570,3,Rejected,315.980392,Keshav Acharya,Keshav,Acharya
27,Indira Joshi,50,76985,454,3,Rejected,503.169935,Indira Joshi,Indira,Joshi
28,Bikram Kandel,31,111523,568,0,Approved,728.908497,Bikram Kandel,Bikram,Kandel
29,Nirmala Baral,38,19342,502,1,Rejected,126.418301,Nirmala Baral,Nirmala,Baral
30,Kishor Katuwal,22,52621,538,3,Rejected,343.928105,Kishor Katuwal,Kishor,Katuwal
31,Anita Sapkota,27,61263,605,3,Approved,400.411765,Anita Sapkota,Anita,Sapkota
32,Rajan Dhital,27,48509,559,1,Rejected,317.052288,Rajan Dhital,Rajan,Dhital
33,Meena Devkota,57,41749,703,1,Approved,272.869281,Meena Devkota,Meena,Devkota
34,Kumar Bhusal,26,98913,783,0,Approved,646.490196,Kumar Bhusal,Kumar,Bhusal
35,Sabitri Paudel,34,16309,654,2,Rejected,106.594771,Sabitri Paudel,Sabitri,Paudel
36,Yubraj Koirala,52,23299,467,3,Rejected,152.281046,Yubraj Koirala,Yubraj,Koirala
37,Sita Ojha,52,120054,300,3,Rejected,784.666667,Sita Ojha,Sita,Ojha
38,Prem Bogati,34,131654,550,1,Approved,860.483660,Prem Bogati,Prem,Bogati
39,Kalpana Aryal,47,81908,497,2,Approved,535.346405,Kalpana Aryal,Kalpana,Aryal
40,Tika Rimal,54,31792,599,1,Rejected,207.790850,Tika Rimal,Tika,Rimal
41,Uma Bhusal,48,132441,493,2,Approved,865.627451,Uma Bhusal,Uma,Bhusal
42,Dilip Bhandari,54,46017,641,0,Rejected,300.764706,Dilip Bhandari,Dilip,Bhandari
43,Champa Dhungana,47,136601,793,2,Approved,892.816993,Champa Dhungana,Champa,Dhungana
44,Khem Wagle,37,120552,598,1,Approved,787.921569,Khem Wagle,Khem,Wagle
45,Sarala Chapagain,24,86147,707,2,Approved,563.052288,Sarala Chapagain,Sarala,Chapagain
46,Bal Gautam,29,55125,814,2,Approved,360.294118,Bal Gautam,Bal,Gautam
47,Purnima Nepal,55,20240,420,1,Rejected,132.287582,Purnima Nepal,Purnima,Nepal
48,Ashok Rijal,30,27868,665,0,Rejected,182.143791,Ashok Rijal,Ashok,Rijal
49,Hema Poudyal,52,31528,774,3,Approved,206.065359,Hema Poudyal,Hema,Poudyal

In [182]:
data1 = [
    {'name':'Hem', 'age':23},
    {'name':'Raj'},
    {'name':'Ramesh','age':45}
]

In [183]:
df = pd.DataFrame(data1)

In [184]:
df

     name   age
0     Hem  23.0
1     Raj   NaN
2  Ramesh  45.0

In [185]:
df.isnull()

    name    age
0  False  False
1  False   True
2  False  False

In [186]:
df.dropna()  #delete null

     name   age
0     Hem  23.0
2  Ramesh  45.0

In [187]:
df.drop(columns=['name'])

    age
0  23.0
1   NaN
2  45.0