In [1]:
import pandas as pd

In [2]:
var = pd.DataFrame(
    [
        [1,2,3,4,5],
        ['a','b','c','d','e']
    ]
)

In [3]:
print(var)

   0  1  2  3  4
0  1  2  3  4  5
1  a  b  c  d  e

In [4]:
var.shape

(2, 5)

In [5]:
var.columns = ['c1','c2','c3','c4','c5']

In [6]:
var

  c1 c2 c3 c4 c5
0  1  2  3  4  5
1  a  b  c  d  e

In [7]:
var.index = ['A','B']

In [8]:
var

  c1 c2 c3 c4 c5
A  1  2  3  4  5
B  a  b  c  d  e

In [9]:
var.rename(columns={'c5':'col5'})

  c1 c2 c3 c4 col5
A  1  2  3  4    5
B  a  b  c  d    e

In [10]:
var.rename(index={'B':'row2'})

     c1 c2 c3 c4 c5
A     1  2  3  4  5
row2  a  b  c  d  e

In [20]:
stu_details = {
     "name":['Hem','Rajan','Mahesh'],
     "age":[23,21,22],
     "address":['KTM','Dhn','Mnr']
    }

In [21]:
df = pd.DataFrame(stu_details)

In [25]:
df

     name  age address
0     Hem   23     KTM
1   Rajan   21     Dhn
2  Mahesh   22     Mnr

In [26]:
df.columns = ['Name','Age','Address']   #to change the column name

In [27]:
df

     Name  Age Address
0     Hem   23     KTM
1   Rajan   21     Dhn
2  Mahesh   22     Mnr

In [28]:
df.index = ['R1','R2','R3']   #to change the index(Row) name

In [29]:
df

      Name  Age Address
R1     Hem   23     KTM
R2   Rajan   21     Dhn
R3  Mahesh   22     Mnr

In [30]:
df.rename(columns={"Name":"Stu-Name"})   #fixed column name change

   Stu-Name  Age Address
R1      Hem   23     KTM
R2    Rajan   21     Dhn
R3   Mahesh   22     Mnr

In [31]:
df.rename(index={'R1':'Row1'})  #fixed index name change

        Name  Age Address
Row1     Hem   23     KTM
R2     Rajan   21     Dhn
R3    Mahesh   22     Mnr

In [33]:
df

      Name  Age Address
R1     Hem   23     KTM
R2   Rajan   21     Dhn
R3  Mahesh   22     Mnr

In [35]:
marks = pd.Series([12,23,43,45])  #creates a series

In [36]:
marks

0    12
1    23
2    43
3    45
dtype: int64

In [38]:
# reading data from the file

In [39]:
# reading csv file
df = pd.read_csv('annual-ent.csv')

In [40]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [41]:
df.head()   #first five row data

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [43]:
df.tail()  #last 5 rows

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [46]:
df.shape  #(rows, columns)

(60255, 10)

In [47]:
df.columns #columns name

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='str')

In [48]:
df.index #index

RangeIndex(start=0, stop=60255, step=1)

In [51]:
df.info()  #summary of dataframe

<class 'pandas.DataFrame'>
RangeIndex: 60255 entries, 0 to 60254
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         60255 non-null  int64
 1   Industry_aggregation_NZSIOC  60255 non-null  str
 2   Industry_code_NZSIOC         60255 non-null  str
 3   Industry_name_NZSIOC         60255 non-null  str
 4   Units                        60255 non-null  str
 5   Variable_code                60255 non-null  str
 6   Variable_name                60255 non-null  str
 7   Variable_category            60255 non-null  str
 8   Value                        60255 non-null  str
 9   Industry_code_ANZSIC06       60255 non-null  str
dtypes: int64(1), str(9)
memory usage: 4.6 MB

In [58]:
df['Year']  #selecting single column

0        2025
1        2025
2        2025
3        2025
4        2025
         ...
60250    2013
60251    2013
60252    2013
60253    2013
60254    2013
Name: Year, Length: 60255, dtype: int64

In [59]:
df[['Year','Units']]  #selecting multiple columns

       Year               Units
0      2025  Dollars (millions)
1      2025  Dollars (millions)
2      2025  Dollars (millions)
3      2025  Dollars (millions)
4      2025  Dollars (millions)
...     ...                 ...
60250  2013          Percentage
60251  2013          Percentage
60252  2013          Percentage
60253  2013          Percentage
60254  2013          Percentage

[60255 rows x 2 columns]

In [60]:
# selecting rows

In [66]:
df.loc[0]

Year                                                                        2025
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     976077
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [70]:
df.loc[0:4]   #selecting multiple rows

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [71]:
df.loc[2:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [84]:
df.loc[2:4,["Year","Variable_code"]]   #row and column selection

   Year Variable_code
2  2025           H05
3  2025           H07
4  2025           H08

In [85]:
# Position-based selection
df.iloc

In [86]:
df.iloc[0:4]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...

In [87]:
df.iloc[1,3]  #selecting cell using row and column index

'All industries'