In [124]:
import pandas as pd

In [125]:
df = pd.read_excel('file_example_XLSX_50.xlsx')

In [126]:
df.head()

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [127]:
df.tail()

     0 First Name   Last Name  Gender        Country  Age        Date    Id
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [128]:
df.loc[1:2]

   0 First Name  Last Name  Gender        Country  Age        Date    Id
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587

In [129]:
df.loc[:1]

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582

In [130]:
df.iloc[2,3]

'Male'

In [131]:
df.loc[2:3,['First Name','Last Name']]

  First Name Last Name
2     Philip      Gent
3   Kathleen    Hanner

In [132]:
# filtering in pandas

df[df['Age']>50]

     0 First Name Last Name  Gender        Country  Age        Date    Id
4    5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
6    7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
21  22      Holly      Eudy  Female  United States   52  16/08/2016  8561

In [133]:
df[(df['Gender']=='Male') & (df['Age'] >30)]

     0 First Name Last Name Gender        Country  Age        Date    Id
2    3     Philip      Gent   Male         France   36  21/05/2015  2587
11  12   Franklyn    Unknow   Male         France   38  15/10/2017  2579
28  29      Garth     Gangi   Male  United States   41  16/08/2016  3256
34  35     Dewitt    Borger   Male  United States   36  21/05/2015  8514
39  40      Chase    Karner   Male  United States   37  15/10/2017  2154
48  49     Jeromy      Danz   Male  United States   39  15/10/2017  3265

In [134]:
# df.isnull()

In [135]:
# df.isna()

In [136]:
df.isnull().sum()

0             0
First Name    0
Last Name     0
Gender        0
Country       0
Age           0
Date          0
Id            0
dtype: int64

In [137]:
# df.notnull()

In [138]:
df = df.drop(columns=["Id"])

In [139]:
df.head()

   0 First Name  Last Name  Gender        Country  Age        Date
0  1      Dulce      Abril  Female  United States   32  15/10/2017
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016
2  3     Philip       Gent    Male         France   36  21/05/2015
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017
4  5    Nereida    Magwood  Female  United States   58  16/08/2016

In [140]:
# replace
df['Gender'] = df['Gender'].replace({'Male':'M','Female':'F'})

In [141]:
df.head()

   0 First Name  Last Name Gender        Country  Age        Date
0  1      Dulce      Abril      F  United States   32  15/10/2017
1  2       Mara  Hashimoto      F  Great Britain   25  16/08/2016
2  3     Philip       Gent      M         France   36  21/05/2015
3  4   Kathleen     Hanner      F  United States   25  15/10/2017
4  5    Nereida    Magwood      F  United States   58  16/08/2016

In [144]:
# apply
df['First Name'] = df['First Name'].apply(lambda x: x.upper())

In [145]:
df.head()

   0 First Name  Last Name Gender        Country  Age        Date
0  1      DULCE      Abril      F  United States   32  15/10/2017
1  2       MARA  Hashimoto      F  Great Britain   25  16/08/2016
2  3     PHILIP       Gent      M         France   36  21/05/2015
3  4   KATHLEEN     Hanner      F  United States   25  15/10/2017
4  5    NEREIDA    Magwood      F  United States   58  16/08/2016

In [146]:
df['Full Name'] = df['First Name']+ ' ' +df['Last Name']

In [147]:
df.head()

,0,First Name,Last Name,Gender,Country,Age,Date,Full Name
0,1,DULCE,Abril,F,United States,32,15/10/2017,DULCE Abril
1,2,MARA,Hashimoto,F,Great Britain,25,16/08/2016,MARA Hashimoto
2,3,PHILIP,Gent,M,France,36,21/05/2015,PHILIP Gent
3,4,KATHLEEN,Hanner,F,United States,25,15/10/2017,KATHLEEN Hanner
4,5,NEREIDA,Magwood,F,United States,58,16/08/2016,NEREIDA Magwood

In [152]:
# df[['FName','LName']] = df['Full Name'].str.split(' ', expand=True)

In [154]:
# df.head()